spring.application.name=livestream-api

server.port=8080
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/sweetandkarak
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.jpa.show-sql=true

spring.mvc.static-path-pattern=/uploads/**
app.jwt.secret=C6UlILsE6GJwNqwCTkkvJj9O653yJUoteWMLfYyrc3vaGrrTOrJFAUD1wEBnnposzcQl
app.jwt.expiration=86400000



spring.web.resources.static-locations=file:uploads/,classpath:/static/
spring.jpa.open-in-view=true
logging.level.org.springframework.security=DEBUG

app.upload.dir=uploads/

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=84f1139a0abcda
spring.mail.password=410d9f8f403eb4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true