spring.application.name=sweetandkarak

server.port = 8080
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/dawoodSweets
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.jpa.show-sql=true